//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbarV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NovedadesUsuarios
    {
        public int Id { get; set; }
        public string TipoNovedad { get; set; }
        public Nullable<System.DateTime> FechaNovedad { get; set; }
        public Nullable<System.DateTime> FechaFacturado { get; set; }
        public string Nombres { get; set; }
        public string Cedula { get; set; }
        public string NumeroDias { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Area { get; set; }
        public Nullable<int> IdArea { get; set; }
        public string Operacion { get; set; }
        public Nullable<int> IdOperacion { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public string Concepto { get; set; }
        public string Jurado { get; set; }
        public string Horario { get; set; }
        public string NombreBackup { get; set; }
        public string Motivo { get; set; }
        public string Ususario { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
        public Nullable<int> IdPersona { get; set; }
    }
}
