//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbarV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int PersonaId { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string nombres { get; set; }
        public string cedula { get; set; }
        public System.DateTime fechaDeNacimiento { get; set; }
        public string lugarDeNacimiento { get; set; }
        public string sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> idRh { get; set; }
        public string eps { get; set; }
        public string direccionResidencia { get; set; }
        public string barrio { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string correo { get; set; }
        public string personaDeEmergencia { get; set; }
        public string telefonoDeEmergencia { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<int> idOperacion { get; set; }
        public Nullable<int> idArea { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public Nullable<int> IdSite { get; set; }
        public Nullable<int> nombreTipoContrato { get; set; }
        public Nullable<int> nombreTipoCosto { get; set; }
        public Nullable<int> Salario { get; set; }
        public Nullable<int> supervisorOperativo { get; set; }
        public Nullable<byte> trabajaFestivos { get; set; }
        public Nullable<int> carneDeSitel { get; set; }
        public Nullable<byte> parkEdificio { get; set; }
        public string marcaCarro { get; set; }
        public string colorCarro { get; set; }
        public string placaCarro { get; set; }
        public Nullable<int> NoParkPin { get; set; }
        public string fotoURL { get; set; }
        public Nullable<System.DateTime> fechaRetiro { get; set; }
        public Nullable<int> razonRetiro { get; set; }
        public Nullable<System.DateTime> dateLastUpdate { get; set; }
        public string actualizado { get; set; }
        public Nullable<int> numeroEmpleado { get; set; }
        public string emailCorporativo { get; set; }
        public string puestoNo { get; set; }
        public Nullable<int> extFisica { get; set; }
        public Nullable<int> subBu { get; set; }
        public int idPosting { get; set; }
        public int idUsuario { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Cargos Cargos { get; set; }
        public virtual Operaciones Operaciones { get; set; }
        public virtual Rhs Rhs { get; set; }
        public virtual Sites Sites { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
