//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbarV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int Id { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Nombres { get; set; }
        public string Cedula { get; set; }
        public System.DateTime FechaDeNacimiento { get; set; }
        public string LugarDeNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> IdRh { get; set; }
        public string Eps { get; set; }
        public string DireccionResidencia { get; set; }
        public string Barrio { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public string PersonaDeEmergencia { get; set; }
        public string TelefonoDeEmergencia { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IdOperacion { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public Nullable<int> IdSite { get; set; }
        public Nullable<int> NombreTipoContrato { get; set; }
        public Nullable<int> NombreTipoCosto { get; set; }
        public Nullable<int> Salario { get; set; }
        public Nullable<int> SupervisorOperativo { get; set; }
        public Nullable<byte> TrabajaFestivos { get; set; }
        public Nullable<int> CarneDeSitel { get; set; }
        public Nullable<byte> ParkEdificio { get; set; }
        public string MarcaCarro { get; set; }
        public string ColorCarro { get; set; }
        public string PlacaCarro { get; set; }
        public Nullable<int> NoParkPin { get; set; }
        public string FotoURL { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public Nullable<int> RazonRetiro { get; set; }
        public Nullable<System.DateTime> DateLastUpdate { get; set; }
        public string Actualizado { get; set; }
        public Nullable<int> NumeroEmpleado { get; set; }
        public string EmailCorporativo { get; set; }
        public string PuestoNo { get; set; }
        public Nullable<int> ExtFisica { get; set; }
        public Nullable<int> SubBu { get; set; }
        public int IdPosting { get; set; }
        public int IdUsuario { get; set; }
        public string Status { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Cargos Cargos { get; set; }
        public virtual Operaciones Operaciones { get; set; }
        public virtual Rhs Rhs { get; set; }
        public virtual Sites Sites { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
